Looker embed
dtempx/syphonx-chrome pull request #6
Opened 2023-08-07 18:39 UTC by ps-jspitler

2023-08-11 00:08 UTC, dtempx requested changes

2023-08-11 00:08 UTC, dtempx commented on src/panel/TemplateEditor/DataPanel/PortalView.tsx
> +    useEffect(() => {
Move this into a new PortalContext within the TemplateEditor context such that `panelUrl` comes from `usePortal`.

2023-08-11 00:08 UTC, dtempx commented on src/panel/TemplateEditor/Sidebar/PortalDialog.tsx
> +    useEffect(() => {
Move this into a new PortalContext within the TemplateEditor context such that `dialogUrl` comes from `usePortal`.

2023-08-11 00:08 UTC, dtempx commented on src/panel/Portal.ts
> +    looks?: {
Just use `views`, no need for back compat.

2023-08-11 00:08 UTC, dtempx commented on src/panel/TemplateEditor/lib/cloud/looker.ts
> +    const { url } = await request.json(`/pricespider/looker-embed-url?look=${lookId}&filters=${JSON.stringify(filters)}`);
Make this distinction about looker and pricespider in the cloud, passing the template path and the template params, such that the editor has no knowledge of pricespider or looker. The user context is already defined in the auth, so if you need to know something about for the pricespider you can get that by querying the users collection on the server.

2023-08-16 23:56 UTC, ps-jspitler commented on src/panel/TemplateEditor/lib/cloud/portal.ts
> +export const load = async (params: PortalParams, userId?: string) => {
Should we move this, and `getUser` and other 'new' network calls into syphonx-lib?

2023-08-16 23:56 UTC, ps-jspitler commented on src/panel/TemplateEditor/lib/cloud/user.ts
> +function formatDocument(obj: unknown): unknown {
the cause of some pretty small / hard-to-diagnose issues... the validation of the user... we might move that 100% to servers-side, to reduce this redundancy?

2023-08-17 23:02 UTC, dtempx approved these changes

2023-08-17 23:02 UTC, merged